version: '3.8'
services:
  pustok-api:
    image: shafinhasnat/pustok-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [/usr/src/app/entrypoint.sh]
    volumes:
      - .:/usr/src/app
    expose:
      - 5004
    ports:
      - 5004:5000
    restart: always
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=src.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:pustok@1.2.3.4:5432/pustok